./configure -platform win32-clang-g++ \
-opensource -confirmlicence \
-opengl desktop -skip qtx11extras -skip qtwayland \
-skip qtactiveqt -skip qtandroidextras -skip qtserialbus \
-skip qtdeclarative -skip qtdatavis3d -skip qtcharts \
-skip qtnetworkauth -skip qtmacextras -skip qtvirtualkeyboard \
-skip qt3d -skip qtsensors -skip qtwebengine -skip qtspeech \
-skip qttranslations -skip qtgamepad -skip qtdoc \
-skip qtlottie -skip qtserialport -skip qtquick3d \
-skip qtremoteobjects -skip qtquickcontrols \
-skip qtquickcontrols2 -skip qtquicktimeline \
-skip qtconnectivity -no-compile-examples -release -prefix /c/qt
